package com.nutrisoft.core.shared.component.auth.application.listener;

import com.nutrisoft.core.shared.component.auth.application.RegisterCredentialUseCase;
import com.nutrisoft.core.shared.component.auth.domain.UserRole;
import com.nutrisoft.core.shared.component.patient.PatientEvent;
import java.util.UUID;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Component;

/**
 * Patient Registration Event Listener.
 *
 * <p>Located in: Core\Shared\Component\Auth\Application
 *
 * <p>This component listens to PacienteRegistradoDomainEvent and coordinates the flow: 1. Retrieves
 * the temporarily stored password 2. Executes the RegisterCredentialUseCase 3. Publishes
 * CredencialRegistradaDomainEvent to trigger notification handling
 *
 * <p>This acts as the AuthConsumer in the event flow.
 *
 * <p>Event Flow: RegistrarPaciente -> PacienteRegistradoDomainEvent -> ConsumidorAuth ->
 * RegistrarCedencial -> CredencialRegistradaDomainEvent -> ConsumidorNotificacion ->
 * EnviarCorreoElectronico
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class PatientRegistrationEventListener {
  private final RegisterCredentialUseCase registerCredentialUseCase;
  private final ApplicationEventPublisher eventPublisher;

  /**
   * Handle patient registration event and execute credential registration.
   *
   * <p>This method is called after the transaction is committed, ensuring the Patient aggregate has
   * been persisted. Creates a credential with an autogenerated password.
   *
   * @param event The PatientCreatedEvent
   */
  @EventListener
  public void handlePatientRegistrationEvent(final PatientEvent.PatientCreatedEvent event) {
    log.info("Handling patient registration event for email: {}", event.email());
    try {
      // Parse the aggregate ID
      UUID aggregateId = UUID.fromString(event.getAggregateId());

      // Execute credential registration (password is autogenerated inside Credential.create())
      registerCredentialUseCase.execute(aggregateId, event.email(), UserRole.PATIENT);
      log.info("Credential registered successfully for patient: {}", event.email());
    } catch (Exception e) {
      log.error("Error handling patient registration event for user: {}", event.email(), e);
      // Don't throw exception - this is an async operation
    }
  }
}
