package com.nutrisoft.core.shared.component.auth.application.listener;

import com.nutrisoft.core.shared.component.auth.application.RegisterCredentialUseCase;
import com.nutrisoft.core.shared.component.auth.domain.UserRole;
import com.nutrisoft.core.shared.component.professional.ProfessionalEvent;
import java.util.UUID;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Component;
import org.springframework.transaction.event.TransactionalEventListener;

/**
 * Professional Registration Event Listener.
 *
 * <p>Located in: Core\Shared\Component\Auth\Application
 *
 * <p>This component listens to ProfessionalRegisteredEvent and coordinates the flow: 1. Retrieves
 * the temporarily stored password 2. Executes the RegisterCredentialUseCase 3. Publishes
 * CredencialRegistradaDomainEvent to trigger notification handling
 *
 * <p>This acts as the AuthConsumer in the event flow.
 *
 * <p>Event Flow: RegistrarProfesional -> ProfessionalRegisteredEvent -> ConsumidorAuth ->
 * RegistrarCedencial -> CredencialRegistradaDomainEvent -> ConsumidorNotificacion ->
 * EnviarCorreoElectronico
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class ProfessionalRegistrationEventListener {
  private final RegisterCredentialUseCase registerCredentialUseCase;
  private final ApplicationEventPublisher eventPublisher;

  /**
   * Handle professional registration event and execute credential registration.
   *
   * <p>This method is called after the transaction is committed, ensuring the Professional
   * aggregate has been persisted. Creates a credential with an autogenerated password.
   *
   * @param event The ProfessionalCreatedEvent
   */
  @EventListener
  public void handleProfessionalRegistrationEvent(
      final ProfessionalEvent.ProfessionalCreatedEvent event) {
    log.info("Handling professional registration event for email: {}", event.email());
    try {
      // Parse the aggregate ID
      UUID aggregateId = UUID.fromString(event.aggregateId());

      // Execute credential registration (password is autogenerated inside Credential.create())
      registerCredentialUseCase.execute(aggregateId, event.email(), UserRole.PROFESSIONAL);
      log.info("Credential registered successfully for professional: {}", event.email());
    } catch (Exception e) {
      log.error("Error handling professional registration event for user: {}", event.email(), e);
      // Don't throw exception - this is an async operation
    }
  }
}
