package com.nutrisoft.infrastructure.notification.service;

import java.util.Map;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.thymeleaf.ITemplateEngine;
import org.thymeleaf.context.Context;

/**
 * Email Template Service.
 *
 * <p>Located in: Infrastructure\Notification\Service
 *
 * <p>Responsibility: Provide utilities for rendering HTML email templates using Thymeleaf. This
 * service processes template files and injects variables into them.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class EmailTemplateService {

  private final ITemplateEngine templateEngine;

  /**
   * Render an email template with the provided variables.
   *
   * @param templateName The name of the template file (e.g., "welcome-email")
   * @param variables A map of variable names and their values
   * @return The rendered HTML content
   */
  public String renderTemplate(String templateName, Map<String, Object> variables) {
    try {
      Context context = new Context();
      context.setVariables(variables);

      String htmlContent = templateEngine.process("emails/" + templateName, context);
      log.debug("Template '{}' rendered successfully", templateName);
      return htmlContent;
    } catch (Exception e) {
      log.error("Error rendering template '{}': {}", templateName, e.getMessage(), e);
      throw new RuntimeException("Failed to render email template: " + templateName, e);
    }
  }

  /**
   * Render the welcome email template.
   *
   * @param email The user's email address
   * @param password The autogenerated password
   * @return The rendered HTML welcome email content
   */
  public String renderWelcomeEmailTemplate(String email, String password) {
    Map<String, Object> variables = new java.util.HashMap<>();
    variables.put("email", email);
    variables.put("password", password);

    return renderTemplate("welcome-email", variables);
  }
}
