package com.nutrisoft.core.shared.component.auth.domain;

import com.nutrisoft.core.port.out.auth.PasswordHasher;
import com.nutrisoft.core.shared.component.common.Email;
import java.security.SecureRandom;
import java.util.UUID;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

/**
 * Domain Service: Credential Factory.
 *
 * <p>Located in: Core\Shared\Component\Auth\Domain\Service
 *
 * <p>Responsibility: Create new Credential aggregates with proper password generation and hashing.
 * This service encapsulates the logic for: - Generating random plaintext passwords - Hashing
 * passwords using the PasswordHasher port - Creating properly initialized Credential aggregates -
 * Publishing domain events
 *
 * <p>This is a domain service (not an application service) because it handles domain logic for
 * credential creation, which is a core business process.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class CredentialFactory {

  private final PasswordHasher passwordHasher;

  /**
   * Create a new Credential aggregate with autogenerated and hashed password.
   *
   * <p>This method: 1. Generates a random plaintext password 2. Hashes the plaintext password using
   * the PasswordHasher 3. Creates and returns a new Credential aggregate 4. The credential will
   * have both plainPassword and passwordHash fields
   *
   * @param aggregateId The ID of the aggregate (Patient, Professional, etc.)
   * @param email The email (must be unique)
   * @param role The user role (PATIENT, PROFESSIONAL, ADMIN)
   * @return A new Credential aggregate with generated and hashed password
   */
  public Credential createCredential(UUID aggregateId, Email email, UserRole role) {
    log.debug("Creating credential for email: {}", email.value());

    String plainPassword = generateRandomPassword();
    String passwordHash = passwordHasher.hash(plainPassword);

    Credential credential =
        Credential.create(aggregateId, email, plainPassword, passwordHash, role);

    log.debug("Credential created successfully for email: {}", email.value());
    return credential;
  }

  /**
   * Generate a random plaintext password.
   *
   * <p>Creates a 16-character random password using uppercase, lowercase, digits, and special
   * characters for increased entropy.
   *
   * @return A random plaintext password string
   */
  private String generateRandomPassword() {
    final String CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*";
    final int PASSWORD_LENGTH = 16;
    SecureRandom random = new SecureRandom();
    StringBuilder password = new StringBuilder();

    for (int i = 0; i < PASSWORD_LENGTH; i++) {
      password.append(CHARS.charAt(random.nextInt(CHARS.length())));
    }

    return password.toString();
  }
}
