package com.nutrisoft.core.shared.component.auth.domain;

import com.nutrisoft.core.shared.component.common.Email;
import com.nutrisoft.core.shared.ddd.AggregateRoot;
import java.time.LocalDateTime;
import java.util.UUID;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NonNull;

/**
 * Credential Aggregate Root. Represents authentication credentials for a user. This aggregate
 * manages credentials that can be associated with any domain aggregate (Patient, Professional,
 * etc.) via their ID (aggregateId).
 *
 * <p>Located in: Core\Shared\Component\Auth\Domain
 *
 * <p>Responsibility: Manage credential lifecycle including creation, password updates, and
 * activation/deactivation.
 *
 * <p>NOTE: Credentials do NOT represent a User entity (which doesn't exist in DDD). Instead, they
 * hold authentication data linked to domain aggregates.
 *
 * <p>PASSWORD FIELDS: - plainPassword: Plaintext password (autogenerated, used for events and email
 * notifications) - passwordHash: BCrypt hashed password (used for authentication and database
 * storage)
 *
 * <p>CREDENTIAL CREATION: Use CredentialFactory domain service to create credentials. The factory
 * handles password generation and hashing in one operation.
 */
@Getter
@EqualsAndHashCode(callSuper = false)
public class Credential extends AggregateRoot<CredentialId> {
  // FIXME: aggegateId should be an AggregateRootId
  private final UUID aggregateId; // ID of the aggregate (Patient, Professional, etc.)
  private final Email email;
  private String passwordHash; // BCrypt hashed password
  private final UserRole role;
  private final LocalDateTime createdAt;
  private LocalDateTime updatedAt;
  private boolean active;

  public Credential(
      @NonNull CredentialId id,
      @NonNull UUID aggregateId,
      @NonNull Email email,
      @NonNull String passwordHash,
      @NonNull UserRole role,
      @NonNull LocalDateTime createdAt,
      LocalDateTime updatedAt,
      boolean active) {
    super(id);
    this.aggregateId = aggregateId;
    this.email = email;
    this.passwordHash = passwordHash;
    this.role = role;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
    this.active = active;
  }

  /**
   * Package-private static factory method to create a new Credential.
   *
   * <p>This method is NOT public because credential creation should always go through
   * CredentialFactory domain service.
   */
  static Credential create(
      @NonNull UUID aggregateId,
      @NonNull Email email,
      @NonNull String plainPassword,
      @NonNull String passwordHash,
      @NonNull UserRole role) {
    final var now = LocalDateTime.now();
    final var credential =
        new Credential(
            CredentialId.create(),
            aggregateId,
            email,
            passwordHash,
            role,
            now,
            now,
            true);

    credential.registerEvent(
        new CredentialEvent.CredentialCreatedDomainEvent(
            credential.getId().value().toString(),
            credential.email.value(),
            plainPassword,
            now));

    return credential;
  }

  /**
   * Update the password for this credential.
   *
   * @param newPasswordHash The new encoded password hash
   */
  public void updatePassword(@NonNull String newPasswordHash) {
    this.passwordHash = newPasswordHash;
    this.updatedAt = LocalDateTime.now();
    // Register event for password update
    this.registerEvent(
        new CredentialEvent.CredentialPasswordUpdatedEvent(
            this.getId().value().toString(), this.email.value(), this.updatedAt));
  }

  /** Deactivate this credential. */
  public void deactivate() {
    this.active = false;
    this.updatedAt = LocalDateTime.now();
    // Register event for credential deactivation
    this.registerEvent(
        new CredentialEvent.CredentialDeactivatedEvent(
            this.getId().value().toString(), this.email.value(), this.updatedAt));
  }

  /** Activate this credential. */
  public void activate() {
    this.active = true;
    this.updatedAt = LocalDateTime.now();
    // Register event for credential activation
    this.registerEvent(
        new CredentialEvent.CredentialActivatedEvent(
            this.getId().value().toString(), this.email.value(), this.updatedAt));
  }
}
