package com.nutrisoft.core.shared.component.auth.application;

import java.util.UUID;

import com.nutrisoft.core.port.out.eventbus.EventBus;
import com.nutrisoft.core.port.out.auth.CredentialRepository;
import com.nutrisoft.core.shared.component.auth.domain.Credential;
import com.nutrisoft.core.shared.component.auth.domain.CredentialFactory;
import com.nutrisoft.core.shared.component.auth.domain.UserRole;
import com.nutrisoft.core.shared.component.common.Email;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Use Case: Register a new Credential.
 *
 * <p>Located in: Core\Shared\Component\Auth\Application\UseCase
 *
 * <p>Responsibility: Handle the business logic for credential registration. This is a
 * shared/transversal use case that orchestrates: 1. Credential creation with autogenerated password
 * 2. Credential persistence 3. Domain event publishing
 *
 * <p>NOTE: This use case is called AFTER the domain aggregate has been created and persisted. The
 * aggregateId must refer to an existing aggregate (Patient, Professional, Admin).
 * 
 * <p>The credential is created with an autogenerated random password. This password will be sent to
 * the user via email or other secure channel.
 */
@Slf4j
@Service
@RequiredArgsConstructor
@Transactional
public class RegisterCredentialUseCase {

  private final CredentialFactory credentialFactory;
  private final CredentialRepository credentialRepository;
  private final EventBus eventBus;

  /**
   * Execute the register credential use case.
   *
   * <p>Creates a new credential with an autogenerated random password. The password is NOT taken as
   * a parameter - it is randomly generated by the Credential aggregate.
   *
   * @param aggregateId The ID of the aggregate (Patient, Professional, Admin) that owns this
   *     credential
   * @param email The email (must be unique)
   * @param role The role of the user (PATIENT, PROFESSIONAL, ADMIN)
   * @return The created Credential (with autogenerated password)
   */
  public Credential execute(UUID aggregateId, String email, UserRole role) {

    log.info("Registering credential for {} with role: {}", email, role);

    // Validate email uniqueness
    Email emailVO = Email.of(email);
    if (credentialRepository.existsByEmail(emailVO)) {
      log.warn("Credential registration failed: Email already registered - {}", email);
      throw new IllegalArgumentException("Email is already registered");
    }

    // Create credential using CredentialFactory (handles password generation and hashing)
    Credential credential = credentialFactory.createCredential(aggregateId, emailVO, role);

    // Persist credential
    credentialRepository.save(credential);
    log.info("Credential successfully registered for email: {} with role: {}", email, role);

    eventBus.publish(credential.pullDomainEvents());

    return credential;
  }
}
