package com.nutrisoft.core.shared.component.auth.application.notification;

import com.nutrisoft.core.port.out.notifications.Notifications;
import com.nutrisoft.infrastructure.notification.service.EmailTemplateService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;

/**
 * Use Case: Send Welcome Email.
 *
 * <p>Located in: Core\Shared\Component\Notification\Application
 *
 * <p>Responsibility: Handle the business logic for sending welcome emails to newly registered
 * users. This is a transversal use case that sends emails after credential registration.
 *
 * <p>NOTE: This use case is called by notification event listeners after credentials have been
 * created and persisted.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class SendWelcomeEmailUseCase {

  private final Notifications notifications;
  private final EmailTemplateService emailTemplateService;

  /**
   * Execute the send welcome email use case.
   *
   * @param email The user's email address
   * @param password The autogenerated password
   */
  @Async
  public void execute(String email, String password) {
    log.info("Sending welcome email to: {}", email);

    String subject = "Bienvenido a Nutrisoft - ¡Registro Exitoso!";
    String htmlContent = emailTemplateService.renderWelcomeEmailTemplate(email, password);

    notifications.send(email, subject, htmlContent);
    log.info("Welcome email sent successfully to: {}", email);
  }
}
